In [9]:
import geopandas as gp
import pandas as pd
import numpy as np
import json
import os
from requests import Session
import matplotlib.pyplot as plt

In [63]:
varnames = sorted([f"Data/by-vargroup/{name}" for name in os.listdir("Data/by-vargroup") if "csv" in name])
years = sorted(os.listdir("Data/by-vargroup/by-year"))
yrnames = {yr: sorted([f"Data/by-vargroup/by-year/{yr}/{name}" for name in os.listdir(f"Data/by-vargroup/by-year/{yr}")]) for yr in years}
countrynames = sorted([f"Data/by-country/{name}" for name in os.listdir("Data/by-country")])

In [64]:
varkeys = []
countrykeys = []
yrkeys = []

for path in varnames:
    filename = path.split('/')[-1]
    var = filename.replace('.csv','')
    varkeys.append(var)

for path in countrynames:
    filename = path.split('/')[-1]
    country = filename.replace('.csv','')
    countrykeys.append(country)

for yr in years:
    for path in yrnames[yr]:
        filename = path.split('/')[-1]
        var = filename.replace('.csv','')
        yrkeys.append(var)

vartups = [*zip(varkeys,varnames)]
yrtups = {yr: [*zip(yrkeys,yrnames[yr])] for yr in years}
countrytups = [*zip(countrykeys,countrynames)]

In [75]:
byvar = {var[0]: pd.read_csv(var[1],index_col=[0,1,2]) for var in vartups}
byyear = {yr: {var[0]: pd.read_csv(var[1],index_col=[0,1]) for var in yrtups[yr]} for yr in years}
bycountry = {country[0]: pd.read_csv(country[1],index_col=[0,1,2,3]) for country in countrytups}

In [76]:
bycountry['Canada']

,,,,Value,Symbol
Canada,Variable Name,Variable Id,Year,,
0,Total area of the country (excl. coastal water),4100,1962,998467.0,X
1,Total area of the country (excl. coastal water),4100,1967,998467.0,X
2,Total area of the country (excl. coastal water),4100,1972,998467.0,X
3,Total area of the country (excl. coastal water),4100,1977,998467.0,X
4,Total area of the country (excl. coastal water),4100,1982,998467.0,X
...,...,...,...,...,...
408,Harvested irrigated temporary crop area: Fodder,4369,2017,222.7,I
409,Harvested irrigated temporary crop area: Fodder,4369,2018,222.7,I
410,Harvested irrigated temporary crop area: Other crops,4377,2012,13.7,I
411,Harvested irrigated temporary crop area: Other crops,4377,2017,13.7,I
412,Harvested irrigated temporary crop area: Other crops,4377,2018,13.7,I